### ISSUE TITLE
Prepare the engine for release 1.0

### ISSUE THREAD

**Issue by LaszloLango** [Samsung/jerryscript#1125]
This issue is created to collect all the tasks we need to do before the first release of the engine.

### Documentation

- [x] GitHub wiki
- [x] gh-pages (http://samsung.github.io/jerryscript)
- [x] In source documentation
  - [x] Comments in public headers files
  - [x] Markdown files under docs folder (internals doc. and API examples&references)
  - [x] Target porting how-to. See: #1313 

### Jerry API

 - [x] Finalize Jerry API. See: #1148

### Jerry Port API
 - [x] Finalize Jerry Port API. See: #964

### Refactor the build system

 - [x] Create new build system. See: #998, #1192 
 - [x] Provide instructions or automate build for the NuttX/RIOT configuration on the STM32F4 board

### Release criteria

- [x] Regression tests pass on x86-32 Linux
- [x] Regression tests pass on x86-64 Linux
- [x] Regression tests pass on ARMv7 Linux
- [x] SunSpider benchmark produces correct results running on top of NuttX on the STM32F4 board
- [x] RIOT port passes smoke test (running a hello world script)

### Community feedback
- mbed OS 3.0 has been tested and works (running a blinking LED test)
- Various versions of Zephyr have been tested and work (see comments below) 

### Needs testing support/feedback from the community

- ESP8266, see #1264

**Comment by LaszloLango** [comment]
I tried to summarize the TODOs for the planned release. Anyone who has write access feel free to edit the description of the issue. Every comment and suggestion is welcome.

**Comment by seanshpark** [comment]
👍

**Comment by seanshpark** [comment]
Not sure how to explain but how about usage examples something like target porting how-to, small toy project examples, video clips links... ?

**Comment by tilmannOSG** [comment]
I've update the issue to reflect the current status :)

**Comment by polaroi8d** [comment]
Im tested the mbed OS with FRDM-K64F board and the simple blinky example. Its works right :white_check_mark:

**Comment by tilmannOSG** [comment]
@polaroi8d Thanks, that's great to hear! Can you please also mention the git hash of the version that you tested?

**Comment by polaroi8d** [comment]
Im tested the 'JerryScript v1.0 Release Candidate 2' source code from github.com/Samsung/jerryscript/releases site, but there is a hash too: 1e82ae1eb5b9d3da20478b660a326c58f743b586

**Comment by tilmannOSG** [comment]
@polaroi8d I see, we actually merged the Curie support recently (to make sure that it will be part of the 1.0 release), those changes were not part of the RC2 tarball on Friday. Can you please do another test run with the jerryscript-release-1.0.0 branch?  
Thanks in advance!

**Comment by polaroi8d** [comment]
@tilmannOSG with 7f6911103fa99c3231f234cf14fd4465b810c8d1 hash its okey?

**Comment by tilmannOSG** [comment]
@polaroi8d Looks like the hash you mentioned is from trunk, please test with https://github.com/Samsung/jerryscript/tree/jerryscript-release-1.0.0 :)  
The current HEAD in jerryscript-release-1.0.0 is https://github.com/Samsung/jerryscript/commit/04e597a6a4679dc8d59dc73843a03c90d67885ed  
Can you please give it another try? :)

**Comment by bzsolt** [comment]
I've checked the *x86-32 Linux*, *x86-64 Linux* and *ARMv7 Linux* targets with the precommit script (`tools/run-tests.py --precommit`) and everything works fine.
The tested hash is https://github.com/Samsung/jerryscript/commit/04e597a6a4679dc8d59dc73843a03c90d67885ed

**Comment by tilmannOSG** [comment]
@bzsolt Thank you!

**Comment by polaroi8d** [comment]
Sorry @tilmannOSG, now tested with the mentioned 04e597a6a4679dc8d59dc73843a03c90d67885ed hash, everything works fine with this.

**Comment by tilmannOSG** [comment]
@polaroi8d No worries, thanks for doing another round of testing!

**Comment by pfalcon** [comment]
Tested with a smoke test (executing `var test=0; for (t=100; t<1000; t++) test+=t; print ('Hi JS World! '+test);`) following Zephyr targets:

* qemu_x86
* qemu_cortex_cm3
* frdm_k64f (on a real device)

JrS revision used: current HEAD of jerryscript-release-1.0.0 branch, de9c27b12. Zephyr version used: v1.5.0 release (v1.5.0 ig Zephyr repo, 5ca45ba3).

Thanks!

**Comment by jiangzidong** [comment]
Tested in Arduino101 with targer/CurieBSP port, everything works fine.
Jerry hash: [de9c27b](https://github.com/Samsung/jerryscript/commit/de9c27b1226188397b4eac934c598d82755e3aa0)
CurieBSP version: [V3.1.1](https://github.com/CurieBSP/main/releases/tag/v3.1.1)

**Comment by tilmannOSG** [comment]
@pfalcon @jiangzidong Excellent, thanks for the test runs!

**Comment by robertsipka** [comment]
I've tested the RIOT target with stm32f4 board, it works fine!
 Jerry-hash: de9c27b1
 RIOT-hash: 26e4004d

**Comment by bzsolt** [comment]
https://github.com/Samsung/jerryscript/commit/de9c27b1226188397b4eac934c598d82755e3aa0 works well with NuttX on STM32F4 board.

**Comment by LaszloLango** [comment]
@tilmannOSG, I've updated the GitHub wiki. Deleted 2 outdated wiki page (Roadmap and Ideas for improvement) and added references to the in source documentations. We have duplicated wiki pages: https://github.com/Samsung/jerryscript/wiki/Developer's-Certificate-of-Origin and https://github.com/Samsung/jerryscript/wiki/JerryScript-Developer's-Certificate-of-Origin are identical. I think we should keep only one of them. What do you think?

**Comment by tilmannOSG** [comment]
@robertsipka @bzsolt Thanks! Looks like we have test results for all targets now :) (except for ESP8266)

**Comment by tilmannOSG** [comment]
@LaszloLango Excellent, thanks for doing the cleanup. It seems the two DCO pages are identical indeed. As you say, we don't need two of them so I think you can just go ahead and delete https://github.com/Samsung/jerryscript/wiki/Developer's-Certificate-of-Origin.

**Comment by LaszloLango** [comment]
JerryScript 1.0 is out, so we can close this issue.
https://github.com/Samsung/jerryscript/releases/tag/v1.0

**Comment by jiangzidong** [comment]
great! @zherczeg Could you please modify a little bit in the description of  https://github.com/Samsung/jerryscript/releases/tag/v1.0

`Curie on Arduino101`  ==> `Curie BSP on Arduino101`

Because Curie is the SOC (HW) of Arduino101, and CurieBSP is the SDK for Curie Device :)

**Comment by zherczeg** [comment]
Done

**Comment by tilmannOSG** [comment]
@jiangzidong Oh I see, apologies for the mistake :)

**Comment by jiangzidong** [comment]
@tilmannOSG @zherczeg Thanks!
