### ISSUE TITLE
Implement ECMA262 String builtin object

### ISSUE THREAD

**Issue by ILyoan** [Samsung/jerryscript#80]
To track status of progress of String builtin.

See [ECMA262 String](http://www.ecma-international.org/ecma-262/5.1/#sec-15.5) for specification.

Required items

- [x] String()
- [x] new String()
- [x] String.prototype
- [x] String.fromCharCode 
- [x] String.prototype.constructor
- [x] String.prototype.toString( )
- [x] String.prototype.valueOf( )
- [x] String.prototype.charAt() #320 
- [x] String.prototype.charCodeAt() #352
- [x] String.prototype.concat() #159 
- [x] String.prototype.indexOf() #456 
- [x] String.prototype.lastIndexOf() #483
- [x] String.prototype.localeCompare() #386 
- [x] String.prototype.match() #443 
- [x] String.prototype.replace() #474 
- [x] String.prototype.search() #504 
- [x] String.prototype.slice() #138 
- [x] String.prototype.split() #530
- [x] String.prototype.substring() #244 #318 
- [x] String.prototype.toLowerCase() #365 
- [x] String.prototype.toLocaleLowerCase() #365 
- [x] String.prototype.toUpperCase() #365 
- [x] String.prototype.toLocaleUpperCase() #365
- [x] String.prototype.trim() #191
- [x] length

**Comment by galpeter** [comment]
All string built-ins have implementations, closing issue
