### ISSUE TITLE
Implement ECMA262 Number builtin object

### ISSUE THREAD

**Issue by galpeter** [Samsung/jerryscript#83]
Track the Number built in progress.
Related ECMA262 section: http://www.ecma-international.org/ecma-262/5.1/#sec-15.7

- [x] Number(..)
- [x] new Number(..)
- [x] Number.length
- [x] Number.MAX_VALUE
- [x] Number.MIN_VALUE
- [x] Number.NaN
- [x] Number.NEGATIVE_INFINITY
- [x] Number.POSITIVE_INFINITY
- [x] Number.prototype
- [x] Number.prototype.constructor
- [x] Number.prototype.toString(..) #306 
- [x] Number.prototype.toLocaleString()
- [x] Number.prototype.valueOf()
- [x] Number.prototype.toFixed(..) #100 
- [x] Number.prototype.toExponential(..) #224 
- [x] Number.prototype.toPrecision(..) #238

**Comment by egavrin** [comment]
Looks like Number is completed, can we close it?

**Comment by galpeter** [comment]
Yeah it's done, closing issue.
