### ISSUE TITLE
Complete ECMA262 Function object

### ISSUE THREAD

**Issue by galpeter** [Samsung/jerryscript#93]
Related ECMA262 section: http://www.ecma-international.org/ecma-262/5.1/#sec-15.3

- [x] Function(..)
- [x] new Function(..) #174 
- [x] Function.prototype
- [x] Function.length
- [x] Function.prototype.constuctor
- [x] Function.prototype.toString() #165 
- [x] Function.prototype.apply(..) #163 
- [x] Function.prototype.call(..)
- [x] Function.prototype.bind(..) #321 
- [x] .length
- [x] .prototype

**Comment by kkristof** [comment]
I'm closing this issues because all of them have been landed.
