### ISSUE TITLE
Implement ECMA262 Date builtin object

### ISSUE THREAD

**Issue by galpeter** [Samsung/jerryscript#94]
Related ECMA262 section: http://www.ecma-international.org/ecma-262/5.1/#sec-15.9

- [x] Date(..) #322 
- [x] new Date(..) #322 
- [x] Date.prototype
- [x] Date.parse(..) #297 
- [x] Date.UTC(..) #305 
- [x] Date.now() #305 
- [x] Date.prototype.constructor
- [x] Date.prototype.toString() #336 
- [x] Date.prototype.toDateString() #360 
- [x] Date.prototype.toTimeString() #360 
- [x] Date.prototype.toLocaleString() #416
- [x] Date.prototype.toLocaleDateString() #416
- [x] Date.prototype.toLocaleTimeString() #416
- [x] Date.prototype.valueOf()
- [x] Date.prototype.getTime() #334 
- [x] Date.prototype.getFullYear() #334
- [x] Date.prototype.getUTCFullYear() #334
- [x] Date.prototype.getMonth() #334
- [x] Date.prototype.getUTCMonth() #334
- [x] Date.prototype.getDate() #334
- [x] Date.prototype.getUTCDate() #334
- [x] Date.prototype.getDay() #334
- [x] Date.prototype.getUTCDay() #334
- [x] Date.prototype.getHours() #334
- [x] Date.prototype.getUTCHours() #334
- [x] Date.prototype.getMinutes() #334
- [x] Date.prototype.getUTCMinutes() #334
- [x] Date.prototype.getSeconds() #334
- [x] Date.prototype.getUTCSeconds() #334
- [x] Date.prototype.getMilliseconds() #334
- [x] Date.prototype.getUTCMilliseconds() #334
- [x] Date.prototype.getTimezoneOffset() #334
- [x] Date.prototype.setTime(..) #367
- [x] Date.prototype.setMilliseconds(..) #367
- [x] Date.prototype.setUTCmilliseconds(..) #367
- [x] Date.prototype.setSeconds(..) #367
- [x] Date.prototype.setUTCSeconds(..) #367
- [x] Date.prototype.setMinutes(..) #367
- [x] Date.prototype.setUTCMinutes(..) #367
- [x] Date.prototype.setHours(..) #367
- [x] Date.prototype.setUTCHours(..) #367
- [x] Date.prototype.setDate(..) #367
- [x] Date.prototype.setUTCDate(..) #367
- [x] Date.prototype.setMonth(..) #367
- [x] Date.prototype.setUTCMonth(..) #367
- [x] Date.prototype.setFullYear(..) #367
- [x] Date.prototype.setUTCFullYear(..) #367
- [x] Date.prototype.toUTCString(..) #418
- [x] Date.prototype.toISOString() #418
- [x] Date.prototype.toJSON(..) #455
